=== arkivverket/schemas/EPJARK/epjpakkeliste.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://schema.arkivverket.no/apjark/epjpakkeliste"
    xmlns="http://schema.arkivverket.no/epjark/epjpakkeliste" elementFormDefault="qualified"
    xmlns:epj="http://schema.arkivverket.no/apjark/epjpakkeliste">

    <!--	XML-skjema for EPJark epjpakkeliste.xml	(Versjon 0.4 2014-04-08 - eriaab/jengle Arkivverket Riksarkivet/Norsk helsearkiv)	-->

    <xs:element name="epjpakkeliste">
        <xs:annotation>
            <xs:documentation xml:lang="no">
               Samlet informasjonom avleveringen 
           </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AvleveringsID" type="xs:string"
                    default="2.16.578.1.39.100.11.2.1234.5678">
                    <xs:annotation>
                        <xs:documentation>Unik ID for denne avlevering</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="ansvarligPerson" type="xs:string" default="Henrik Arkivar">
                    <xs:annotation>
                        <xs:documentation xml:lang="no">Navn på person ansvarlig for overføring
                                    </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="kontaktInformasjon" type="xs:string"
                    default="henark@friskvik.hsx.no">
                    <xs:annotation>
                        <xs:documentation xml:lang="no">
                                        Oppgi epost, telefon og eventuelt annen relevant info 
                                    </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="beskrivelseLagringsEnhet" type="xs:string" default="NHx">
                    <xs:annotation>
                        <xs:documentation xml:lang="no">
                                        Beskriv overføringen, teknologi, medium etc. 
                                    </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="antallLagringsenheter" type="xs:int" minOccurs="0" default="1">
                    <xs:annotation>
                        <xs:documentation xml:lang="no">
                                        Oppgi antall enheter som brukes i overføringen.
                                        Om ikke annet er oppgitt, antas det ett og bare ett medium.
                                    </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="klarforOverforingDato" type="xs:date" default="2016-03-18">
                    <xs:annotation>
                        <xs:documentation>Dato for når kontaktperson klargjør for, eller foretar overføring</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="pakke" maxOccurs="unbounded" minOccurs="2">
                    <xs:annotation>
                        <xs:documentation xml:lang="no">Dokumentasjon filpakke 
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pakketype" type="epj:pakketypekode">
                                <xs:annotation>
                                    <xs:documentation xml:lang="no">Pakketype (dok eller epj)</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="filReferanse" type="epj:uuidTarFil">
                                <xs:annotation>
                                    <xs:documentation xml:lang="no">
                                        Oppgi navn på overordnet "tar" fil. Skal følge normen 
                                        "UUID.tar", der "UUID" er en gyldig "universally unique identifier".
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="pakketDato" type="xs:date">
                                <xs:annotation>
                                    <xs:documentation xml:lang="no">
                                        Oppgi dato filen ble laget 
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sjekksum" type="epj:sjekksumVerdi"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="pakketypekode">
        <xs:annotation>
            <xs:documentation>Type pakke i avlevering</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(dok|epj)"/>
            <xs:length value="3"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="uuidTarFil">
        <xs:annotation>
            <xs:documentation xml:lang="no">
                Data element med gyldig syntaks sjekk for filnavn "uuid.tar" 
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.tar"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sjekksumVerdi">
        <xs:annotation>
            <xs:documentation xml:lang="no">Data element med gyldig syntakssjekk for generert sjekksum 
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-f]{8,64}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== arkivverket/schemas/EPJARK/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<epjpakkeliste xmlns="http://schema.arkivverket.no/epjark/epjpakkeliste"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://schema.arkivverket.no/epjark/epjpakkeliste 
 file:/J:/Arkivfag/schemas/epjpakkeliste.xsd">
    
    <AvleveringsID>2.16.578.1.39.100.11.2.1234.5678</AvleveringsID>
    <ansvarligPerson>Henrik Arkivar</ansvarligPerson>
    <kontaktInformasjon>henark@friskvik.hsx.no</kontaktInformasjon>
    <beskrivelseLagringsEnhet>NHN</beskrivelseLagringsEnhet>
    <antallLagringsenheter>1</antallLagringsenheter>
    <klarforOverforingDato>2016-03-18</klarforOverforingDato>
    <pakke>
        <pakketype>dok</pakketype>
        <filReferanse>fff8eeba-26aa-2853-f4dd-ec34fb28c81e.tar</filReferanse>
        <pakketDato>2018-04-05</pakketDato>
        <sjekksum>4e29ae5f29ac728b4bfacc12e669878fe509572b0808b112c1447a1539834387</sjekksum>
    </pakke>
    <pakke>
        <pakketype>epj</pakketype>
        <filReferanse>f7abbfb5-7b48-df29-550e-80b1fb7e75e5.tar</filReferanse>
        <pakketDato>2016-10-14</pakketDato>
        <sjekksum>1b3ef4952e87d42eb86077eb1c5b9e5f2c78108c1aa2e980b19981fa0cbfdc86</sjekksum>
    </pakke>
    <pakke>
        <pakketype>epj</pakketype>
        <filReferanse>c0b96193-cecb-1a76-d0d7-df2b0fd6bec8.tar</filReferanse>
        <pakketDato>2017-12-11</pakketDato>
        <sjekksum>62b4b149d8ebdc13ea57319a2bd659d13b4b36c90a034a633fbe05b4f598f729</sjekksum>
    </pakke>
</epjpakkeliste>
